default_context:
  project_name: 'Asyncio Auto Dial'
  project_slug: 'asyncio-auto-dial'
  domain_main: '192.168.1.97'
  domain_staging: 'stag.192.168.1.97'
  docker_swarm_stack_name_main: '192-168-1-97'
  docker_swarm_stack_name_staging: 'stag-192-168-1-97'
  secret_key: 'bc16450d59bff30d3f4615cfd3bb5ed8fddc27ecc08a2ea22c7d5be73d1bce51'
  first_superuser: 'muraigtor@gmail.com'
  first_superuser_password: 'Gfhjkm321'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://192.168.1.97", "http://192.168.1.97:4200", "http://192.168.1.97:3000", "http://192.168.1.97:8080", "https://192.168.1.97", "https://192.168.1.97:4200", "https://192.168.1.97:3000", "https://192.168.1.97:8080", "https://stag.192.168.1.97", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '465'
  smtp_host: 'smtp.google.com'
  smtp_user: 'muraigtor'
  smtp_password: 'Aleksandra21186'
  smtp_emails_from_email: 'muraigtor@gmail.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'Gfhjkm321'
  traefik_constraint_tag: '192.168.1.97'
  traefik_constraint_tag_staging: 'stag.192.168.1.97'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Gfhjkm321'
  sentry_dsn: 'https://github.com/muraig/asyncio_auto_dial/issues'
  docker_image_prefix: 'asyncio'
  docker_image_backend: 'asynciobackend'
  docker_image_celeryworker: 'asyncioceleryworker'
  docker_image_frontend: 'asynciofrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
